import 'package:flutter/material.dart';

class CampusLocation {
  final String id;
  final String name;
  final String description;
  final double latitude;
  final double longitude;
  final IconData icon;

  CampusLocation({
    required this.id,
    required this.name,
    required this.description,
    required this.latitude,
    required this.longitude,
    required this.icon,
  });

  static List<CampusLocation> get allLocations => [
    CampusLocation(
      id: 'irc',
      name: 'Aklatang Emilio Aguinaldo - IRC',
      description: 'Main campus library',
      latitude: 14.3208,
      longitude: 120.9619,
      icon: Icons.local_library,
    ),
    CampusLocation(
      id: 'agh',
      name: 'Ayuntamiento de Gonzales Hall',
      description: 'Administrative building with student services',
      latitude: 14.3206,
      longitude: 120.9629,
      icon: Icons.business,
    ),
    CampusLocation(
      id: 'bahay_pagasa',
      name: 'Bahay Pag-asa',
      description: 'Campus Facility',
      latitude: 14.3266,
      longitude: 120.9564,
      icon: Icons.house,
    ),
    // CampusLocation(
    //   id: 'bed',
    //   name: 'Basic Education',
    //   description: 'School Building',
    //   latitude: 0.0,
    //   longitude: 0.0,
    //   icon: Icons.school_outlined,
    // ),
    CampusLocation(
      id: 'cso',
      name: 'Campus Security Office',
      description: 'Security Services',
      latitude: 14.3244,
      longitude: 120.9590,
      icon: Icons.security,
    ),
    CampusLocation(
      id: 'cth_tirona',
      name: 'Candido Tirona Hall (CTH)',
      description: 'Campus Building',
      latitude: 14.3234,
      longitude: 120.9592,
      icon: Icons.business,
    ),
    CampusLocation(
      id: 'ceat',
      name: 'CEAT Building',
      description: 'College of Engineering, Architecture & Technology',
      latitude: 14.3230,
      longitude: 120.9584,
      icon: Icons.engineering,
    ),
    CampusLocation(
      id: 'library',
      name: 'DLSU-D Library',
      description: 'Main campus library with study areas and resources',
      latitude: 14.3208,
      longitude: 120.9619,
      icon: Icons.local_library,
    ),
    // CampusLocation(
    //   id: 'fdc',
    //   name: 'DLSU-D Faculty Development Cooperative (FDC)',
    //   description: 'Office',
    //   latitude: 0.0,
    //   longitude: 0.0,
    //   icon: Icons.work,
    // ),
    CampusLocation(
      id: 'mah',
      name: 'Doña Marcela De Agoncillo Hall (MAH)',
      description: 'Campus Building',
      latitude: 14.3211,
      longitude: 120.9622,
      icon: Icons.business,
    ),
    CampusLocation(
      id: 'fdh',
      name: 'Dr. Del Mundo Hall (FDH)',
      description: 'Campus Building',
      latitude: 14.3202,
      longitude: 120.9628,
      icon: Icons.business,
    ),
    // CampusLocation(
    //   id: 'ermac',
    //   name: 'ERMAC Building',
    //   description: 'Campus Building',
    //   latitude: 0.0,
    //   longitude: 0.0,
    //   icon: Icons.business,
    // ),
    CampusLocation(
      id: 'fch',
      name: 'Felipe Calderon Hall (FCH)',
      description: 'Campus Building',
      latitude: 14.3222,
      longitude: 120.9596,
      icon: Icons.business,
    ),
    CampusLocation(
      id: 'gate_1',
      name: 'Gate 1',
      description: 'Main entrance to DLSU-D campus',
      latitude: 14.3308,
      longitude: 120.9378,
      icon: Icons.door_front_door,
    ),
    CampusLocation(
      id: 'gate_3',
      name: 'Gate 3',
      description: 'Secondary entrance near sports complex',
      latitude: 14.3282,
      longitude: 120.9569,
      icon: Icons.door_front_door,
    ),
    CampusLocation(
      id: 'gdo',
      name: 'GDO/Grandstand and Track Oval',
      description: 'Sports Facility',
      latitude: 14.3252,
      longitude: 120.9581,
      icon: Icons.sports,
    ),
    CampusLocation(
      id: 'gdh',
      name: 'Gregoria De Jesus Hall (GDH)',
      description: 'Campus Building',
      latitude: 14.3225,
      longitude: 120.9588,
      icon: Icons.business,
    ),
    CampusLocation(
      id: 'gmh',
      name: 'Gregoria Montoya Hall (GMH)',
      description: 'Campus Building',
      latitude: 14.3232,
      longitude: 120.9588,
      icon: Icons.business,
    ),
    CampusLocation(
      id: 'hotel_rafael',
      name: 'Hotel Rafael/Gourmet Hall/ Centennial Hall',
      description: 'Hotel and Event Venue',
      latitude: 14.3222,
      longitude: 120.9617,
      icon: Icons.hotel,
    ),
    CampusLocation(
      id: 'ictc',
      name: 'Information and Communications Technology Center (ICTC)',
      description: 'IT Services',
      latitude: 14.3223,
      longitude: 120.9629,
      icon: Icons.computer,
    ),
    CampusLocation(
      id: 'jfh',
      name: 'Julian Felipe Hall',
      description: 'Main academic building with classrooms and faculty offices',
      latitude: 14.3211,
      longitude: 120.9626,
      icon: Icons.school,
    ),
    CampusLocation(
      id: 'kabalikat',
      name: 'Kabalikat ng DLSU-D',
      description: 'Office',
      latitude: 14.3236,
      longitude: 120.9597,
      icon: Icons.group_work,
    ),
    CampusLocation(
      id: 'ldh',
      name: 'Ladislao Diwa Hall (LDH)',
      description: 'Campus Building',
      latitude: 14.3225,
      longitude: 120.9597,
      icon: Icons.business,
    ),
    // CampusLocation(
    //   id: 'llc',
    //   name: 'Language Learning Center',
    //   description: 'Academic Center',
    //   latitude: 0.0,
    //   longitude: 0.0,
    //   icon: Icons.language,
    // ),
    CampusLocation(
      id: 'cafeteria',
      name: 'Main Cafeteria',
      description: 'Campus dining facility with various food options',
      latitude: 14.3275,
      longitude: 120.9392,
      icon: Icons.restaurant,
    ),
    CampusLocation(
      id: 'dormitories',
      name: 'Male and Female Dormitories',
      description: 'Student Residences',
      latitude: 14.3210,
      longitude: 120.9600,
      icon: Icons.night_shelter,
    ),
    CampusLocation(
      id: 'mlh',
      name: 'Maria Salome Lianera Hall (MLH)',
      description: 'Campus Building',
      latitude: 14.3237,
      longitude: 120.9582,
      icon: Icons.business,
    ),
    CampusLocation(
      id: 'malvarez',
      name: 'Mariano Alvarez Hall',
      description: 'Campus Building',
      latitude: 14.3218,
      longitude: 120.9630,
      icon: Icons.business,
    ),
    CampusLocation(
      id: 'mth',
      name: 'Mariano Trias Hall (MTH)',
      description: 'Campus Building',
      latitude: 14.3237,
      longitude: 120.9587,
      icon: Icons.business,
    ),
    CampusLocation(
      id: 'museo',
      name: 'Museo De La Salle/Camarin',
      description: 'University Museum',
      latitude: 14.3210,
      longitude: 120.9610,
      icon: Icons.museum,
    ),
    CampusLocation(
      id: 'polca',
      name: 'Parents Organization of La Salle Cavite (POLCA)',
      description: 'Office',
      latitude: 14.3222,
      longitude: 120.9599,
      icon: Icons.group,
    ),
    CampusLocation(
      id: 'pch',
      name: 'Paulo Campos Hall (PCH)',
      description: 'Campus Building',
      latitude: 14.3209,
      longitude: 120.9628,
      icon: Icons.business,
    ),
    CampusLocation(
      id: 'pbh',
      name: 'Purificacion Borromeo Hall (PBH)',
      description: 'Campus Building',
      latitude: 14.3210,
      longitude: 120.9626,
      icon: Icons.business,
    ),
    CampusLocation(
      id: 'residencia',
      name: 'Residencia De San Miguel',
      description: 'Campus Building',
      latitude: 14.3203,
      longitude: 120.9619,
      icon: Icons.home,
    ),
    CampusLocation(
      id: 'rcc',
      name: 'Retreat and Conference Center',
      description: 'Event Venue',
      latitude: 14.3275,
      longitude: 120.9567,
      icon: Icons.meeting_room,
    ),
    CampusLocation(
      id: 'sah',
      name: 'Santiago Alvarez Hall (SAH)',
      description: 'Campus Building',
      latitude: 14.3232,
      longitude: 120.9583,
      icon: Icons.business,
    ),
    CampusLocation(
      id: 'sdah',
      name: 'Severino De Las Alas Hall',
      description: 'Campus Building',
      latitude: 14.3227,
      longitude: 120.9610,
      icon: Icons.business,
    ),
    CampusLocation(
      id: 'uls',
      name: 'Ugnayang La Salle',
      description: 'University multi-purpose sports complex',
      latitude: 14.3269,
      longitude: 120.9573,
      icon: Icons.sports_basketball,
    ),
    CampusLocation(
      id: 'chapel',
      name: 'University Chapel',
      description: 'A quiet place for reflection and prayer',
      latitude: 14.3260,
      longitude: 120.9592,
      icon: Icons.church,
    ),
    CampusLocation(
      id: 'food_square',
      name: 'University Food Square',
      description: 'Dining Area',
      latitude: 14.3215,
      longitude: 120.9601,
      icon: Icons.fastfood,
    ),
    // CampusLocation(
    //   id: 'uro',
    //   name: 'University Research Office',
    //   description: 'Office',
    //   latitude: 0.0,
    //   longitude: 0.0,
    //   icon: Icons.science,
    // ),
    CampusLocation(
      id: 'vbh',
      name: 'Vito Belarmino Hall (VBH)',
      description: 'Campus Building',
      latitude: 14.3221,
      longitude: 120.9592,
      icon: Icons.business,
    ),
  ];
}
